# Generated by Django 5.1.5 on 2025-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/duae8oyif/image/upload/v1753288950/default-img_z02qp1.jpg', upload_to='profile_images'),
        ),
    ]
