# Generated by Django 5.1.5 on 2025-05-30 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL),
        ),
    ]
