# Generated by Django 5.1.5 on 2025-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/duae8oyif/image/upload/v1753288848/default-img_tprf5k.jpg', null=True, upload_to='events_image'),
        ),
    ]
