# Generated by Django 5.1.5 on 2025-02-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
    ]
