# Generated by Django 5.1.5 on 2025-07-26 19:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/duae8oyif/image/upload/v1753288848/default-img_tprf5k.jpg', max_length=255, null=True, verbose_name='Event Images'),
        ),
    ]
