# Generated by Django 5.1.5 on 2025-02-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events_image/default-img.jpg', null=True, upload_to='events_image'),
        ),
    ]
